### ISSUE TITLE
ModuleNotFoundError: No module named 'SKNet'

### ISSUE THREAD

**Issue by sreecharan31** [summitgao/SAR_CD_MS_CapsNet#2]
It would be great if you could help me with this error

**Comment by lyneingcici** [comment]
So, had you solved this question?

**Comment by lyneingcici** [comment]
> 



> It would be great if you could help me with this error



> It would be great if you could help me with this error

so, had you solved this question?

**Comment by sreecharan31** [comment]
No

**Comment by summitgao** [comment]
I will ask Yunhao Gao to fix the error.

**Comment by sreecharan31** [comment]
Okay, who's Yunhao Gao?
