### ISSUE TITLE
Could you please tell me how to get the Sulzberger data set?

### ISSUE THREAD

**Issue by ilixinyu** [summitgao/SAR_CD_MS_CapsNet#3]
Could you please tell me how to get the Sulzberger data set?
I noticed that your article used the Sulzberger data set to compare related methods. However, I  can not find it through the network. Could you please submit it or give us a website to download it?

**Comment by summitgao** [comment]
In our recent work, some reviewers comment that the the ground truth labels of Sulzberger dataset are not accurate enough. Hence, we do not plan to release the dataset.
